Port gui
hypherionmc/EnderCore pull request #9
Opened 2021-08-06 13:59 UTC by jamesblack3

- Uncommented the file
- Changed GlStateManager to RenderSystem where possible
- Changed the scale factor calculation to use the MainWindow's getGuiScaleFactor function
- The tex function in the BufferBuilder uses floats now instead of doubles
- RenderSystem uses color4f instead of color
- Some of the RenderSystem functions names changed and are deprecated, may want to look at those at a later date
- Button.id doesn't exist anymore. Need to use IPressable in the constructor of buttons. Not sure if this file needs it or if that can be done instead by the other modules that are creating the buttons

2021-08-10 18:18 UTC, Rover656 requested changes
I trust that all the rendering stuff will work fine; I'm not an expert here so I'll allow anyone else to chip in. I just think these couple areas should be addressed to make these complete.

2021-08-10 18:18 UTC, Rover656 commented on src/main/java/com/enderio/core/client/gui/widget/ScrollableListWidget.java
>  //  public void setScrollButtonIds(int scrollUpButtonID, int scrollDownButtonID) {
What does this do; I'm sure its needed for something?

2021-08-10 18:18 UTC, Rover656 commented on src/main/java/com/enderio/core/client/gui/widget/ScrollableListWidget.java
>  //  public void actionPerformed(@Nonnull Button b) {
again, should probably be done as part of this PR.

2021-08-11 12:00 UTC, jamesblack3 commented on src/main/java/com/enderio/core/client/gui/widget/ScrollableListWidget.java
>  //  public void setScrollButtonIds(int scrollUpButtonID, int scrollDownButtonID) {
I'm not sure. It was already there so I just ported it over.

2021-08-11 12:06 UTC, jamesblack3 commented on src/main/java/com/enderio/core/client/gui/widget/ScrollableListWidget.java
>  //  public void actionPerformed(@Nonnull Button b) {
Are you referring to line 145? The preview isn't clear...

Well if we need to use IPressable in the constructor of the buttons, then I was having trouble finding where the buttons are being made. The original code seems to have the buttons made elsewhere and their IDs get passed in via setScrollButtonIds.

2021-09-18 16:11 UTC, ferriarnus commented
@jamesblack3 are you still working on it? Otherwise I'll give it a go.

2021-09-19 01:03 UTC, jamesblack3 commented
Go ahead, I wasn't really sure what I was doing.

2021-10-01 18:46 UTC, Macleykun commented
> Go ahead, I wasn't really sure what I was doing.

perhaps you can better close the pull?

2021-10-01 19:18 UTC, closed without merging